name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm i
      - name: Run test
        run: npm test
