name: Release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.5.3
        id: release
        with:
          token: ${{ secrets.BOT_TOKEN }}
          release-type: node
          package-name: 'react-wafer'
          bump-minor-pre-major: Yes
      - uses: actions/checkout@v2
        # These if statements ensure that a publication only occurs when a new release is created
        if: ${{ steps.release.outputs.release_created }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_BOT_TOKEN }}
